export const careerCopy = {
  tr: {
    loading: "Kariyer alanı hazırlanıyor...",
    title: "Kariyer Takibi",
    subtitle: "Üniversite puan ve GNO alanı",
    newUniversity: "Yeni Üniversite",
    university: "Üniversite",
    term: "Dönem",
    course: "Ders",
    selectUniversity: "Üniversite seç",
    noUniversityYet: "Henüz üniversite yok",
    universities: "Üniversiteler",
    newTerm: "Yeni Dönem",
    gpa: "GNO",
    weight: "Ağırlık",
    degree: "Derece",
    myTerms: "Dönemlerim",
    passFail: "Geçme/Kalma",
    letterGrades: "Harf Notları",
    passFailOnly: "Geçti / Kaldı",
    year: "Yıl",
    addTerm: "Dönem Ekle",
    noTermYet: "Henüz dönem yok",
    deleteTerm: "Dönemi sil",
    deleteTermDescription: (termLabel: string) =>
      `${termLabel} dönemi ve içindeki tüm dersler silinecek.`,
    newTermLabel: "Yeni dönem",
    myCourses: "Derslerim",
    newCourse: "Yeni Ders",
    courseName: "Ders adı",
    courseNamePlaceholder: "Örn. أساسيات الحاسوب",
    courseMode: "Ders şekli",
    addCourse: "Ders Ekle",
    noCourseYet: "Henüz ders yok",
    deleteCourse: "Dersi sil",
    deleteCourseDescription: (courseName: string) =>
      `${courseName} dersi ve tüm puan kayıtları silinecek.`,
    newCourseLabel: "Yeni ders",
    score: "Puan",
    letter: "Harf",
    coefficient: "Katsayı",
    passed: "Geçti",
    failed: "Kaldı",
    waitingStatus: "Durum bekliyor",
    passing: "Geçiyor",
    atRisk: "Riskte",
    currentScore: "Güncel puan",
    target: "Hedef",
    scoreTracking: "Puan Takibi",
    pointsSummary: (score: string, max: string) => `${score} / ${max} puan`,
    resetDefault: "Varsayılan",
    earned: "Aldığı",
    outOf: "Üzerinden",
    deleteAssessmentPart: "Puan kalemini sil",
    deleteAssessmentPartDescription: (label: string) =>
      `"${label}" puan kalemi silinecek.`,
    deletePart: "Kalemi sil",
    newAssessmentPart: "Yeni kalem",
    addAssessmentPart: "Puan Kalemi",
    courseSettings: "Ders Ayarları",
    passTarget: "Geçme hedefi (%)",
    letterGradeTitle: "Harf Notu",
    outsideGpaCourse: "Ortalama dışı ders",
    passStatusTitle: "Geçme Durumu",
    selectGrade: "Harf notu seç",
    selectStatus: "Durum seç",
    statusColumn: "Durum",
    gpaDegree: "GNO Derecesi",
    belowTwo: "2 altı",
    letterGradeTracking: "Harf Notu Takibi",
    gradedCoursesSummary: (graded: number, credits: number) =>
      `${graded} notlu ders · ${credits} ağırlık`,
    outOfFour: "4 üzerinden",
    outsideGpaShort: "Ortalama dışı",
    symbolSystem: "Harf Notu Sistemi",
    gpaGaugeLabel: "4 üzerinden GNO göstergesi",
    noGradeYet: "Henüz not yok",
    graded: "Notlu",
    coursesSummary: (count: number, credits: number) =>
      `${count} ders · ${credits} ağırlık`,
    weightSuffix: "ağırlık",
    coefficientLabel: (value: string) => `Katsayı: ${value}`,
    deleteCancel: "İptal",
    deleteConfirm: "Sil",
    deleteIrreversible: "Bu işlem geri alınamaz. Devam etmek istiyor musunuz?",
    gradingSystem: "Harf sistemi",
    universitiesCatalog: {
      "jordan-university": {
        name: "Ürdün Üniversitesi",
        nameAr: "الجامعة الأردنية",
      },
    },
    seasons: {
      first: "1. Dönem",
      second: "2. Dönem",
      summer: "Yaz Dönemi",
    },
    modes: {
      face: "Yüz yüze",
      hybrid: "Yarı online",
      online: "Online",
    },
    assessments: {
      midterm: "Vize",
      participation: "Derse katılım ve ödevler",
      final: "Final",
    },
    gpaRatings: {
      excellent: "Mükemmel",
      veryGood: "Çok İyi",
      good: "İyi",
      acceptable: "Geçer",
      weak: "Zayıf",
    },
    pageTitle: "Kariyer Takibi",
    pageDescription:
      "Üniversite dönemlerini, ders puanlarını, geçme durumunu ve harf notu ortalamasını takip et.",
  },
  ar: {
    loading: "جارٍ تجهيز صفحة المسار الجامعي...",
    title: "المسار الجامعي",
    subtitle: "متابعة الدرجات والمعدل التراكمي",
    newUniversity: "جامعة جديدة",
    university: "الجامعة",
    term: "الفصل",
    course: "المقرر",
    selectUniversity: "اختر الجامعة",
    noUniversityYet: "لا توجد جامعة بعد",
    universities: "الجامعات",
    newTerm: "فصل جديد",
    gpa: "المعدل",
    weight: "الساعات",
    degree: "التقدير",
    myTerms: "فصولي",
    passFail: "النجاح والرسوب",
    letterGrades: "الدرجات الحرفية",
    passFailOnly: "ناجح / راسب",
    year: "السنة",
    addTerm: "إضافة فصل",
    noTermYet: "لا يوجد فصل بعد",
    deleteTerm: "حذف الفصل",
    deleteTermDescription: (termLabel: string) =>
      `سيتم حذف فصل ${termLabel} وجميع المقررات بداخله.`,
    newTermLabel: "فصل جديد",
    myCourses: "مقرراتي",
    newCourse: "مقرر جديد",
    courseName: "اسم المقرر",
    courseNamePlaceholder: "مثال: أساسيات الحاسوب",
    courseMode: "نمط المقرر",
    addCourse: "إضافة مقرر",
    noCourseYet: "لا يوجد مقرر بعد",
    deleteCourse: "حذف المقرر",
    deleteCourseDescription: (courseName: string) =>
      `سيتم حذف مقرر ${courseName} وجميع سجلات الدرجات.`,
    newCourseLabel: "مقرر جديد",
    score: "الدرجة",
    letter: "الرمز",
    coefficient: "المعامل",
    passed: "ناجح",
    failed: "راسب",
    waitingStatus: "بانتظار الحالة",
    passing: "ناجح حاليا",
    atRisk: "معرض للرسوب",
    currentScore: "الدرجة الحالية",
    target: "الحد الأدنى",
    scoreTracking: "متابعة الدرجات",
    pointsSummary: (score: string, max: string) => `${score} / ${max} درجة`,
    resetDefault: "الافتراضي",
    earned: "المحصّل",
    outOf: "من",
    deleteAssessmentPart: "حذف بند الدرجة",
    deleteAssessmentPartDescription: (label: string) =>
      `سيتم حذف بند الدرجة "${label}".`,
    deletePart: "حذف البند",
    newAssessmentPart: "بند جديد",
    addAssessmentPart: "بند درجة",
    courseSettings: "إعدادات المقرر",
    passTarget: "حد النجاح (%)",
    letterGradeTitle: "الدرجة الحرفية",
    outsideGpaCourse: "مقرر خارج المعدل",
    passStatusTitle: "حالة النجاح",
    selectGrade: "اختر الدرجة الحرفية",
    selectStatus: "اختر الحالة",
    statusColumn: "الحالة",
    gpaDegree: "تقدير المعدل",
    belowTwo: "أقل من 2",
    letterGradeTracking: "متابعة الدرجات الحرفية",
    gradedCoursesSummary: (graded: number, credits: number) =>
      `${graded} مقرر مُقيّم · ${credits} ساعة`,
    outOfFour: "من 4",
    outsideGpaShort: "خارج المعدل",
    symbolSystem: "نظام الرموز",
    gpaGaugeLabel: "مؤشر المعدل من 4",
    noGradeYet: "لا توجد درجات بعد",
    graded: "مُقيّم",
    coursesSummary: (count: number, credits: number) =>
      `${count} مقرر · ${credits} ساعة`,
    weightSuffix: "ساعة",
    coefficientLabel: (value: string) => `المعامل: ${value}`,
    deleteCancel: "إلغاء",
    deleteConfirm: "حذف",
    deleteIrreversible: "لا يمكن التراجع عن هذا الإجراء. هل تريد المتابعة؟",
    gradingSystem: "نظام الحروف",
    universitiesCatalog: {
      "jordan-university": {
        name: "Ürdün Üniversitesi",
        nameAr: "الجامعة الأردنية",
      },
    },
    seasons: {
      first: "الفصل الأول",
      second: "الفصل الثاني",
      summer: "الفصل الصيفي",
    },
    modes: {
      face: "حضوري",
      hybrid: "شبه حضوري",
      online: "عن بُعد",
    },
    assessments: {
      midterm: "اختبار منتصف الفصل",
      participation: "المشاركة والواجبات",
      final: "الاختبار النهائي",
    },
    gpaRatings: {
      excellent: "ممتاز",
      veryGood: "جيد جدًا",
      good: "جيد",
      acceptable: "مقبول",
      weak: "ضعيف",
    },
    pageTitle: "المسار الجامعي",
    pageDescription:
      "تابع الفصول الدراسية ودرجات المقررات وحالة النجاح والمعدل التراكمي.",
  },
} as const;

export type CareerCopy = (typeof careerCopy)[keyof typeof careerCopy];
